// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYoh-EWAxxrm-25D0-tdx7o_-e0PsasNI',
    appId: '1:354874994860:web:2e21d0a86c050e8c0c2f09',
    messagingSenderId: '354874994860',
    projectId: 'crud2-23d62',
    authDomain: 'crud2-23d62.firebaseapp.com',
    storageBucket: 'crud2-23d62.appspot.com',
    measurementId: 'G-08XEEQ8FKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRPA6iFjt9zMHgnuKKJ6Il8mmKxaJiO_8',
    appId: '1:354874994860:android:aebe615420a44fe20c2f09',
    messagingSenderId: '354874994860',
    projectId: 'crud2-23d62',
    storageBucket: 'crud2-23d62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAShrrMO5l-OtU9tufqyqW-v5b6c7uy8tM',
    appId: '1:354874994860:ios:48ab512c5a9bd9130c2f09',
    messagingSenderId: '354874994860',
    projectId: 'crud2-23d62',
    storageBucket: 'crud2-23d62.appspot.com',
    iosBundleId: 'com.example.crud',
  );
}
